name: Wallet example

on:
  push:
    branches: [main, buildnet]

jobs:
  run-wallet-example:
    defaults:
      run:
        working-directory: ./

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm install



      - name: Execute tests
        run: |
          if npm run test-wallet ; then
            echo "Successful execution!"
          else
            echo "Failed to execute contracts ..."
            exit 1
          fi
        env:
          JSON_RPC_URL_PUBLIC: ${{ secrets.JSON_RPC_URL_PUBLIC }}
          JSON_RPC_URL_PRIVATE: ${{ secrets.JSON_RPC_URL_PRIVATE }}
          DEPLOYER_SECRET_KEY: ${{ secrets.DEPLOYER_SECRET_KEY }}
          RECEIVER_SECRET_KEY: ${{ secrets.RECEIVER_SECRET_KEY }}